dist: xenial
language: python
cache: pip
matrix:
  fast_finish: true
  include:
    - name: "Python 3.7 on Linux"
      python: 3.7
    - name: "Python 3.6 on Linux"
      if: branch = master
      python: 3.6
    - name: "Python 3.8 on Linux"
      if: branch = master
      python: 3.8
    - name: "macOS"
      if: branch = master
      os: osx
      osx_image: xcode11
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Windows"
      if: branch = master
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH PYTHONIOENCODING=utf8
install:
 - "pip3 install --editable .[dev]"
 - node -v
 - npm install
 - npm run build
script:
 - pylint unicodeit --disable=fixme
 - pylint tests/*.py --disable=fixme
 - pytest -vv
 - npm run lint
 - npm run test
